### PR TITLE
Prune repository files to consildate chapters

### PR DESCRIPTION
**Pull request by semioticrobotic**
This PR suggests pruning repository contents in advance of a planned writing workshop at SCaLE 18x (see #14).

I have consolidated the guidebook's files. Only guidebook **chapters** should have their own files; previously, however, **sections** and **topics** also had their own files, leading to a potentially overwhelming abundance of material in the repository.

The next step will be consolidating even further those files that already contain some guidebook materials into chapters designated on [the outline](https://github.com/theopensourceway/guidebook/blob/master/OUTLINE.adoc).

### CODE REVIEW

**Comment by shaunix** [comment]
Three points:

1) You say only chapters should have files, but this has files for sections. (Which, I think is the way it should be, but I want to clarify.)

2) Can we preserve the information about what topics are in each section somewhere other than git history? I know we want to allow that to evolve, but there's valuable brain output there. Maybe as comments in the section files?

3) It might make sense to rename the section files to include the parent chapter, like `introduction_community_101.adoc`. Unless that would put that into the output file names, because that would be awful. The downside of doing this is that it means renames when reorganizing. But git renames are cheap and trackable, and that's a low cost to pay for less mental overhead for daily editing.

**Comment by semioticrobotic** [comment]
Thanks, @shaunix. Great questions here. Let me address each in turn.

> * You say only chapters should have files, but this has files for sections. (Which, I think is the way it should be, but I want to clarify.)

I do maintain that only chapters should have files. If chapters for sections still exist, it's simply because I missed them during my first pass at pruning. I can try again and make another commit later today to clarify this. Thanks for catching it. I should add, too, that if you know a technical (or any other, really) reason that files for sections will be critical or just beneficial, please do push back on the decision to eliminate them. (I get the sense that you're suggesting section files that contain lists of chapters to be included in those sections, an idea I quite like!)
 
> * Can we preserve the information about what topics are in each section somewhere other than git history? I know we want to allow that to evolve, but there's valuable brain output there. Maybe as comments in the section files?

I agree and have tried to preserve these. In cases where chapters in the initial outline contained some brainstormed topics, I reproduced those suggested topics in the text of the issue related to the chapter. One example would be #33, which suggests a chapter on community health and offers three suggested topics for that chapter, all culled from the original book outline. Happy to try a different tack if we need to.

> * It might make sense to rename the section files to include the parent chapter, like `introduction_community_101.adoc`. Unless that would put that into the output file names, because that would be awful. The downside of doing this is that it means renames when reorganizing. But git renames are cheap and trackable, and that's a low cost to pay for less mental overhead for daily editing.

I agree that some kind of file renaming is going to be important. I had the same thought about that "downside" to lengthier file names and wasn't sure how others felt. Another consideration is the fact that chapters might migrate into different sections from edition to edition, or that different versions of the book (e.g., @quaid proposed "Getting Started" primer version of the book) might have chapters that don't correspond to the same sections they would in the full-length version.

But again, all this is speculative and I'm happy to experiment with other potential best practices going forward! Let me take another spin through the repository and commit another change or two for your review. Thanks again.

**Comment by shaunix** [comment]
> I do maintain that only chapters should have files. If chapters for sections still exist, it's simply because I missed them during my first pass at pruning.

All right, perhaps we're not on the same terminology then. What term would you use for "Introductions" and what term would you use for "Community 101"?

**Comment by semioticrobotic** [comment]
I would call "Introductions" a section (like "Attracting Users" or "Measuring Success"). I would call "Community 101" a chapter in the "Introductions" section (like "Terminology and Lexicon," also a proposed chapter in that section).

**Comment by semioticrobotic** [comment]
Okay, @shaunix! Commit [85251cf](https://github.com/theopensourceway/guidebook/pull/39/commits/85251cf21a5aaf1c0033a46f0ff6a5e2a9e3e943) corrects these inconsistencies. It also begins the work of consolidating already-written materials into chapters officially listen on the outline. For example, see now the chapter on "Legal and governance," which now includes writing on the topic of conducting community elections (already submitted upstream from @dneary).

**Comment by quaid** [comment]
Discussion so far here seems poignant, I only have one thing to +1:

> (I get the sense that you're suggesting section files that contain lists of chapters to be included in those sections, an idea I quite like!)

That seems like a nice idea, an in repo way to see how a bundle might be organized.

Would it be interesting to have alternate bundle files/ToCs?

I guess I can see that there would be value in the right circumstances to seeing a detailed ToC that includes what topics are in a chapter, but not put forth as a thing to be daunted by. This goes back to what @shaunix asked about capturing the original outline as ideas.

**Comment by semioticrobotic** [comment]
> That seems like a nice idea, an in repo way to see how a bundle might be organized. Would it be interesting to have alternate bundle files/ToCs? I guess I can see that there would be value in the right circumstances to seeing a detailed ToC that includes what topics are in a chapter, but not put forth as a thing to be daunted by. This goes back to what @shaunix asked about capturing the original outline as ideas.

Like this idea! I will update the PR again with corresponding section files so we have them in place. The files will contain a list of chapters currently included in that section. As chapters get finished, I'd love to be able to update section files with definitive lists of the topics covered in each chapter, too.

**Comment by semioticrobotic** [comment]
Alrighty then. Commits [fce68b8](https://github.com/theopensourceway/guidebook/pull/39/commits/fce68b8efce032daec4228be2c4e586cf16bc0c9) and [aad6172](https://github.com/theopensourceway/guidebook/pull/39/commits/aad6172a0694ea45ef3aa88f3a36a07b642e81c7) perform the work of establishing section placeholders and updating some additional files accordingly.

I also tried something with commit [fce68b8](https://github.com/theopensourceway/guidebook/pull/39/commits/fce68b8efce032daec4228be2c4e586cf16bc0c9): Since @quaid accepted #20 into the master branch, I decided to put that text into the appropriate upstream file here, too. I was hoping it would help us avoid the "conflicts that must be resolved," as GitHub appears to put it below. Alas, that did not work. But know that the material in that file is the same. Eventually, I will just move that material to a more suitable chapter (i.e., something officially on the outline).

**Comment by quaid** [comment]
I think this is all making a lot of sense. I'm in favor of merging this commit, can you resolve the conflict first? It would be good to land all this so more of these granular discussions of what is in and how we name section files (for example) are in their own pull requests (I reckon, yeah?).

**Comment by semioticrobotic** [comment]
> I think this is all making a lot of sense. I'm in favor of merging this commit, can you resolve the conflict first? It would be good to land all this so more of these granular discussions of what is in and how we name section files (for example) are in their own pull requests (I reckon, yeah?).

Absolutely agree. I recognize that I'm cutting a few corners in an attempt to prepare the repository for the imminent writing sprint

**Pull request merged**
