### PR TITLE
Update chapter on project and community governance

### PR DESCRIPTION
**Pull request by semioticrobotic**
This PR adds substantial material to the chapter on project and community governance. Authors @dneary, @jberkus, and @semioticrobotic contributed.

Note that in addition to the usual editorial guidance, the authors also seek advice on additional subjects the "Conducting basic governance" section might address.

### CODE REVIEW

**Comment by shaunix** [comment]
Do we have style guidelines for emphasizing text? There's a mix of italics and bold in this PR that doesn't make much sense to me.

**Comment by dneary** [comment]
I am unaware of style guidelines, but would be happy to discover them, if they exist. What is your suggestion for emphasis - all italics, or all bold?

**Comment by semioticrobotic** [comment]
That's on me. I'd **bolded** keywords and definitions to mimic a textbook, then _italicized_ words and phrases for emphasis in the prose. Happy to adopt whatever.

**Comment by jwflory** [comment]
This would be an excellent resource to highlight in the chapter, if it is not already:

https://communityrule.info/

I'll try to take a cursory glance over this if I end up with some extra time. Cool to see this being worked on.

**Comment by semioticrobotic** [comment]
This is cool! Thanks, @jwflory.

**Comment by samus-aran** [comment]
Linking this PR with the original issue raised (so we have context and ability to close issues when completed).

*linked to issue #30*

**Review by bproffitt — APPROVED** [review]
Based on criteria for draft review, this chapter is ready to be merged into main

**Pull request merged**
