### PR TITLE
Update community_governance.adoc

### PR DESCRIPTION
**Pull request by bproffitt**
@semioticrobotic @dneary @jberkus Please review development edits.

### CODE REVIEW

**Comment by semioticrobotic** [comment]
Thanks for these! They're great, and I am working on addressing them.

@bproffitt: Could you add a little extra context for the change you're requesting with this comment:

> This feels like an unanswered question: if not governance, what?

Thanks.

**Comment by bproffitt** [comment]
@semioticrobotic It's not super clear in the diff, but that comment was aimed at 

"While documenting these functions is useful, these are not, strictly speaking, governance issues."

If they are not governance issues, what are they?

**Comment by semioticrobotic** [comment]
Ah! Great. Thanks for that. Will tap @jberkus on the virtual shoulder and ask how he might answer your question (I *think* he wrote that particular sentence).

**Comment by jberkus** [comment]
That wasn't actually my original wording.  My original text said:

"While documenting these functions is useful, they are not governance."

Adding "issues" on the end completely changes the meaning of the sentence.  Like "who gets to speak for the project" *is* a governance issue (or, rather, a right), but it is not governance itself.

Maybe we should revert to that text?

**Comment by jberkus** [comment]
+1 on the rest of Brian's edits.

**Comment by semioticrobotic** [comment]
> That wasn't actually my original wording. My original text said:
> 
> "While documenting these things is useful, they are not governance."
> 
> Adding "issues" on the end completely changes the meaning of the sentence. Like "who gets to speak for the project" _is_ a governance issue (or, rather, a right), but it is not governance itself.
> 
> Maybe we should revert to that text?

Ah! Thanks for this, @jberkus. Yes, I will revert and clarify further.

**Comment by semioticrobotic** [comment]
@bproffitt: As far as I can tell, we've accepted all proposed edits and resolved all outstanding issues save for one: the issue of whether or how to write concluding material. But I believe we'll only be able to resolve this when the project itself issues more guidance or comes to come consensus about what's desirable here. I feel confident speaking for the authors when I say that we're happy to tailor the conclusion so it aligns with the other chapters.

**Comment by quaid** [comment]
I did the work in the reverse order by accident; I didn't realize this PR was still open. I manually merged the two versions, favoring the styling changes I had made in my edit through.

**Pull request merged**
