### PR TITLE
Initial outline identifying main chapters of Community Manager Self-C…

### PR DESCRIPTION
**Pull request by samus-aran**
…are section

Proposing the outline for this Community Manager Self-Care section. 

I also include a bit of the basis of each section below but felt it wasn't quite ready for a PR (unless you disagree).

Alot of this is interconnected so any sections that should best suit a different flow I'm up for some feedback (as always).  I also think that is a very personal topic so having the potential of interviews and case studies/experiences would be integral but also we should be respectful that is may be a difficult to approach others to discuss. :)

    1. Community Manager Self-Care
        i. Importance of Self-Care
            (a) Leaders around the clock
                1. Leading a community has it’s unique level of stress usually more intense and interpersonal than other roles due to the nature of working and interacting with diverse personalities: conflict; strategic decisions; lack of motivated members and self-care of others. 
            (b) Being human
                1. Being a leader often implies the need to always be in control and being invincible – no body is perfect.
                2. Identifying that being human is required to be a community manager and being proactive in helping yourself helps others.
            (c) Types of Self-Care
                1. Physical, Mental, Spiritual
        ii. Burnout
            (a) Look out for symptoms
                1. Understand the common symptoms and teach members to be aware of them in others. Grow a network of support within the community. There may be a time when your community sees it in you.
            (b) Preventing/Treating Burnout
                1. Hard to detect and harder to prevent. The goal is to reduce its occurrence and develop a sense of trust between members and an acceptance of being vulnerable is OK.
                2. Stepping away from responsibility is OK and to how to approach your direct reports (both up and down).
        iii. Work/Life Balance
            (a) Addiction
                1. Detecting addiction within yourself and identifying the apparent need to achieve goals or objectives. Consequences and sacrifices addiction causes.
                2. Don’t take too much on. Focus on quality than quantity.
            (b) Maintain boundaries
                1. Balance and moderation is key to a healthy lifestyle both work and play time. Being transparent and honest by identifying clear distinctions of downtime is important for both yourself and community. Set up escalation processes to handle absences or “emergency” contact aswell as the community’s expectation of timely response.
        iv. Self-Reflection
            (a) Through the looking glass
                1. Lack of self-care can cause distortions on how we perceive ourselves as leaders. We understand the importance of reflection on a professional level by conducting constructive feedback with members but we should aim to apply the same retrospective look at ourselves: what makes us happy and provides us a sense of purpose within our role.
            (b) Tackling Impostor Syndrome
                1. Explaining the different patterns and symptoms of Impostor Syndrome.
                2. Utilising self-reflection to acknowledge achievements and positively reconsider your perception of success and failure.
            (c) Network of Support
                1. Reach out to peers, friends or family to build a network of trust and safety to speak honestly about issues, doubts or in some cases a haven to just release tension. Usually they are the first ones to spot if you are acting differently.
        v. Sustainability
            (a) Routine is key
                1. Setting a realistic schedule and frequent rewards to help increase happiness and sense of purpose both within the role and out.
                2. Only thing that is consistent is time. Interests and passions change so what may work previously may have less of an impact later. Strive to dedicate time explicitly for self-care and reflection.
            (b) The Support of the Community
                1. Building a foundation of support and incentives for the community to encourage themselves and you to take frequent leaves of absence to re-charge. Ideally processes established to easily, or as much as possible, delegate some of your or members projects or responsibility among the teams. This will help reduce the feeling of abandonment and the common phase “I can’t just leave!”
        vi. Disclaimer
            (a) Important to note that this isn’t medical advice and if you are concerned you are showing signs of burnout, please consult a doctor.

### CODE REVIEW

**Comment by semioticrobotic** [comment]
I love :heart: the look of this, @samus-aran. Thanks so much for your care in putting it together.

One initial bit of feedback might be to suggest that the "sustainability" section and the "work/life balance" sections be somehow combined. The "sustainability" topics seem to me like great advice for achieve work/life balance (_sustaining_ that balance, if you will!).

Otherwise, I've not much to add here, I'm afraid. What a great addition the guidebook.

To clarify: Are we thinking this will be a _section_ on community manager self-care, and that each of the proposed sub-topics (burnout, balance, reflect, etc.) will be their own individual guidebook _chapters_? Or are we imagining this as a single chapter on self-case, placed in [a pre-existing section](https://github.com/theopensourceway/guidebook/blob/master/OUTLINE.adoc), with each of the topics listed here acting as chapter sub-topics?

**Comment by sparklingrobots** [comment]
This looks great! Thank you for putting it together. 

The only part I had questions about was the section on addiction -- addiction to the work? To something else? 

I agree with @semioticrobotic that the section on sustainability could be combined with the work/life balance section.

**Comment by samus-aran** [comment]
Thanks @semioticrobotic !

I agree that we can combine the Work/Life and Sustainability sub-chapters together.

Propose that the sub-chapter Sustainability be included within Work/Life and the 

iii. Work/Life Balance
        (a) Addiction
            1. Detecting addiction within yourself and identifying the apparent need to achieve goals or objectives. Consequences and sacrifices addiction causes.
            2. Don’t take too much on. Focus on quality than quantity.
        (b) Maintain boundaries
            1. Balance and moderation is key to a healthy lifestyle both work and play time. Being transparent and honest by identifying clear distinctions of downtime is important for both yourself and community. Set up escalation processes to handle absences or “emergency” contact aswell as the community’s expectation of timely response.
        (c) Sustainability
             1. Setting a realistic schedule and frequent rewards to help increase happiness and sense of purpose both within the role and out.
             2. Only thing that is consistent is time. Interests and passions change so what may work previously may have less of an impact later. Strive to dedicate time explicitly for self-care and reflection.
             3. Building a foundation of support and incentives for the community to encourage themselves and you to take frequent leaves of absence to re-charge. Ideally processes established to easily, or as much as possible, delegate some of your or members projects or responsibility among the teams. This will help reduce the feeling of abandonment and the common phase “I can’t just leave!”



In regards to the high level structure I tried to keep the subchapters to a level of two max. I feel that the Community Manager Self-Care would be a single chapter with 2 levels of subchapters. I referred to the Developing A Metrics Plan/Community Metrics to get an idea of the inner subchapters layering: 1, i, a)

Just looking at the https://github.com/theopensourceway/guidebook/blob/master/OUTLINE.adoc (Outline) I see this Chapter as been duplicated, I think it would best sit further down in the list perhaps position 7 (which it currently stands) after Measuring Success - but that's just my preference ^^;

Regarding to Burn Out I agree it could be a separate chapter if taken from the position of members. But if we tackle that topic generally in the self-care I think we could reference it when we discuss other chapters like Defining healthy communities or Avoiding Pitfalls.


@sparklingrobots (love the username btw) Yeah this was to tackle work addiction and identify the possible scenarios of why this occurs e.g. trying to prove yourself, the need for constant communication (the all knowing). It will also go into the consequences of such actions can have on your community and encouraging potential bad habits thus leading to burn out.

I'll make some of the structural changes :+1:

**Comment by semioticrobotic** [comment]
Ah! Thanks, @samus-aran, for pointing out the important fact that the outline lists this chapter twice. Oops!

I have no problem accepting your proposed outline as it stands here. I also your recommendation for positioning the chapter in the overall book. So I'll merge this PR and then do a little tinkering on my end to adjust the ToC, etc.

Thanks much.

**Pull request merged**
