### PR TITLE
Adding writing workflow overview

### PR DESCRIPTION
**Pull request by quaid**
This new content is meant to provide an overview of the writing process so that people coming in have an idea of what is in store for them. It should be detailed enough to be accurate and informative without being overhwhelming and deeply-detailed.

### CODE REVIEW

**Comment by semioticrobotic** [comment]
Just so I'm clear before I review: What is the rationale for not including this in ``CONTRIBUTING.md`` instead?

**Comment by semioticrobotic** [comment]
For example: [Does this make more sense](https://github.com/theopensourceway/guidebook/commit/33a8dcf156b28ef3c47feee3f83d7931f4c5c76f)?

**Comment by quaid** [comment]
I concur with moving this content into CONTRIBUTING.

I think we want to look at how to draw the attention of the reader of the README toward finding the CONTRIBUTING file.

There is a small typo on line 20 of your CONTRIBUTING patch. I'm not yet seeing a way to add that change and bundle the whole thing up to commit. If I don't get to that, would you please?

**Comment by semioticrobotic** [comment]
Thanks, @quaid. I've cleaned this file up now, and it's ready for your final review and merge. Thanks for catching!

**Comment by semioticrobotic** [comment]
Sorry for the typo in the commit explanation. I have no idea what a "coneditorial contribution explanation " is, or why my fingers did that. Suffice it to say I changed the words and stuff.

**Pull request merged**
