### PR TITLE
feat: add creating a culture of mentorship chapter

### PR DESCRIPTION
**Pull request by palante**
- Add new mentorship content
- Port over existing mentorship content found in onboarding, cc @quaid

Edits and improvements are welcome -- thanks!

For additional context, see conversation on https://github.com/theopensourceway/guidebook/pull/176

### CODE REVIEW

**Review by semioticrobotic — APPROVED** [review]
Looks great and all fine with me.

**Review by quaid — APPROVED** [review]
This is great!

The initial flow looks good, the content is a thorough handling for the guidebook at this stage, and I think the structure/integration with existing content looks like it's going to work very well.

We do need to shift the section that I wrote originally from first to third person throughout; we can remove some of the personal observation bits. If you prefer, I can do that editing, should be pretty straightforward for me. (I'll make a note to keep a slot open to do that edit, if needed).

I'm going to approve this merge, then move the tracking issue into the Development Edit column. That is the place were we can do the work to integrate the voice/POV and see if an integrated read through turns up anything else to do for this chapter outside of copyediting. (I don't see off-hand the likelihood for a rewrite of anything else, I'm thinking of if we find a gap we have time to fill, that sort of thing.)

**Comment by palante** [comment]
> We do need to shift the section that I wrote originally from first to third person throughout; we can remove some of the personal observation bits. If you prefer, I can do that editing, should be pretty straightforward for me. (I'll make a note to keep a slot open to do that edit, if needed).

That would be great, thanks @quaid

> That is the place were we can do the work to integrate the voice/POV and see if an integrated read through turns up anything else to do for this chapter outside of copyediting. (I don't see off-hand the likelihood for a rewrite of anything else, I'm thinking of if we find a gap we have time to fill, that sort of thing.)

Good to know, sounds good!

**Comment by quaid** [comment]
I see @rpaik removed the content from the other chapter, so I'm considering that approval of this PR here so he doesn't also have to review this PR too. Let's merge this in now, which typical, but you'll still have to work in your branch.

**Pull request merged**
